DROP TABLE IF EXISTS skaters;

CREATE TABLE skaters (
    team TEXT,
    season INTEGER,
    playerId INTEGER PRIMARY KEY,
    name TEXT,
    position TEXT,
    situation TEXT,
    games_played INTEGER,
    primaryAssists INTEGER,
    secondaryAssists INTEGER,
    shotsOnGoal INTEGER,
    shotAttempts INTEGER,
    points INTEGER,
    goals INTEGER,
    penalties INTEGER,
    penalityMinutes INTEGER,
    hits INTEGER,
    takeaways INTEGER,
    giveaways INTEGER,
    lowDangerGoals INTEGER,
    mediumDangerGoals INTEGER,
    highDangerGoals INTEGER,
    faceoffsWon INTEGER,
    faceoffsLost INTEGER,
    penalityMinutesDrawn INTEGER,
    penaltiesDrawn INTEGER,
    shotsBlockedByPlayer INTEGER,
    OnIce_F_goals INTEGER,
    OnIce_A_goals INTEGER,
);