DROP TABLE IF EXISTS teams;

CREATE TABLE teams (
    team TEXT,
    season INTEGER,
    gameId INTEGER PRIMARY KEY,
    opposingTeam TEXT,
    home_or_away TEXT,
    gameDate INTEGER,
    situation TEXT,
    shotsOnGoalFor INTEGER,
    blockedShotAttemptsFor INTEGER,
    shotAttemptsFor INTEGER,
    goalsFor INTEGER,
    savedShotsOnGoalFor INTEGER,
    penaltiesFor INTEGER,
    penalityMinutesFor INTEGER,
    faceOffsWonFor INTEGER,
    hitsFor INTEGER,
    takeawaysFor INTEGER,
    giveawaysFor INTEGER,
    lowDangerShotsFor INTEGER,
    mediumDangerShotsFor INTEGER,
    highDangerShotsFor INTEGER,
    lowDangerGoalsFor INTEGER,
    mediumDangerGoalsFor INTEGER,
    highDangerGoalsFor INTEGER,
    shotsOnGoalAgainst INTEGER,
    goalsAgainst INTEGER,
    penaltiesAgainst INTEGER,
    penalityMinutesAgainst INTEGER,
    faceOffsWonAgainst INTEGER,
    hitsAgainst INTEGER,
    lowDangerGoalsAgainst INTEGER,
    mediumDangerGoalsAgainst INTEGER,
    highDangerGoalsAgainst INTEGER,
    playoffGame INTEGER
);